# https://rust-lang.github.io/rustfmt/?version=v1.4.36
unstable_features = true
reorder_imports = true
normalize_comments = true
normalize_doc_attributes = true
imports_granularity = "Crate"
format_macro_matchers = true
format_macro_bodies = true
wrap_comments = true
format_code_in_doc_comments = true